package com.ygxhj.mynetty.core.dao;

import com.ygxhj.mynetty.core.model.Player;
import com.ygxhj.mynetty.core.model.PlayerExample;
import java.sql.SQLException;
import java.util.List;

public interface PlayerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int countByExample(PlayerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int deleteByExample(PlayerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    Integer insert(Player record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    Integer insertSelective(Player record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    List selectByExample(PlayerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    Player selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int updateByExampleSelective(Player record, PlayerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int updateByExample(Player record, PlayerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int updateByPrimaryKeySelective(Player record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    int updateByPrimaryKey(Player record) throws SQLException;
}