package com.ygxhj.mynetty.core.model;

import com.ygxhj.mynetty.core.BaseObject;
import java.util.Date;

public class Player extends BaseObject {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player.id
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player.name
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player.create_time
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column player.login_time
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    private Date loginTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player.create_time
     *
     * @return the value of player.create_time
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player.create_time
     *
     * @param createTime the value for player.create_time
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column player.login_time
     *
     * @return the value of player.login_time
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column player.login_time
     *
     * @param loginTime the value for player.login_time
     *
     * @ibatorgenerated Tue Feb 25 10:25:56 CST 2014
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
    
    private long lastMessage;
    
    public long getLastMessage() {
		return lastMessage;
	}

	public void setLastMessage(long lastMessage) {
		this.lastMessage = lastMessage;
	}

	public static final String TABLE_NAME = "player";
}